modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL="https://github.com/REFactoryTeam/MoreMoreLang/issues"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL="https://github.com/REFactoryTeam/MoreMoreLang/"
displayURL = "https://github.com/REFactoryTeam/MoreMoreLang"
logoFile="moremorelang.png"
credits="RemakeFactory"
authors = "${mod_authors}"
displayTest="IGNORE_ALL_VERSION"
description = '''${mod_description}'''
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
